<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-07-14 13:25
=======
# Generated by Django 3.2.5 on 2021-07-12 07:57
>>>>>>> 77f5f6639a9f979429a2f888a4e49322804f60c2

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=1)),
                ('duration', models.IntegerField(default=30)),
            ],
        ),
    ]
